function ah = subplot_label(ax_handle, str)

opos = get(ax_handle, 'OuterPosition');
pos  = get(ax_handle, 'Position');

Fontsize = get(gca, 'Fontsize');
TitleFontSizeMultiplier = get(gca, 'TitleFontSizeMultiplier');

ah = annotation('textbox', [opos(1),pos(4)+pos(2),0,0],...
    'Linestyle', 'none', ...
    'Fontweight', 'bold', ...
    'fontsize', Fontsize * (TitleFontSizeMultiplier + 0.4), ...
    'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'bottom', ...
    'String', str, 'Margin', 0);